### ISSUE TITLE
[Bug]: Cannot invoke "net.minecraft.class_4185.method_25306()"

### ISSUE THREAD

**Issue by xllifi** [ixDarkLorD/ModpackManager#9]
### Describe the Bug

When mod is configured correctly (I hope) it crashes on startup

Config:
```toml
#To sit it properly, visit the mod wiki website for more information:
#https://github.com/ixDarkLorD/ModpackManager/wiki
[Manifest]
	#Modpack Title | Syntax: ${version}, ${mcversion}, ${gamestate}
	title = "KK4 ${version}"
	#Modpack Version
	version = "beta2"
	#Modpack Identifier
	identifier = "KK4"
	project_id_or_url = "https://pastebin.com/raw/W9CdepBF"

[Features]
	#Set it to false, To disable the Window Title Changer
	window_title_changer = false
	#If the Modpack has Sodium/Rubidium mod installed, Set it to true!
	#To prevent crashing from happening by disabling the gamestate syntax
	#This option will be needless if the Window Title Changer feature is disabled!
	safe_title_changer = true
	#CFU Button(Checking for Updates) Behavior
	is_first_time_pressed = false
	#Durability Display Visibility and Size
	durability_display_visibility = false
	#Range: 0.0 ~ 1.0
	durability_display_size = 0.5

[General]
	#Startup Title Visibility and Text
	startup_title_visibility = false
	startup_title_text = "Пожалуйста, ждите! Сборка запускается..."
	#Gamestate Visibility Mode | Syntax: ALL, PLAYING_MODE_AND_EXTRA, PLAYING_MODE_AND_PAUSE_SCREEN, ONLY_PLAYING_MODE
	gamestate_visibility = "ALL"
	#Startup Loading Visibility and Text
	loading_screen_gamestate_visibility = false
	loading_screen_text = "Loading the game..."
```

### To Reproduce

1. Use this config
2. Start the game

### Crash Report or Log

https://mclo.gs/FjnI2Ia

### OS

Windows 11

### Minecraft Version

1.19.2

### ModLoader

Fabric

### Mod Version

0.2.3
